name: Daily Commit Automation

on:
  schedule:
    # Runs every day at 09:15 UTC (specific time, not wildcards)
    - cron: "15 9 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Step for 25f1000098@ds.study.iitm.ac.in
        run: echo "Email step - 25f1000098@ds.study.iitm.ac.in"

      - name: Create daily update file
        run: |
          echo "Daily update: $(date)" >> daily-log.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add daily-log.txt
          git commit -m "Automated daily commit - $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push
